config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  resources :leads
  get '/lead-delete/:id',  to: "leads#destroy"
  get '/signup', to: "users#new"

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	belongs_to :user
	before_save { self.email = email.downcase }
	validates :name, :category, presence: true
	validates :phoneno, presence: true, uniqueness: true, length: { minimum: 8, maximum: 10 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    validates :user_id, presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :leads
	before_save { self.email = email.downcase }
	validates :username, presence: true,
						uniqueness: { case_sensitive: false },
					  length: {minimum: 3, maximum: 25}
					  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
          format: { with: VALID_EMAIL_REGEX },
          uniqueness: true

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  def welcome
  end
end

app/controllers/leads_controller.rb
class LeadsController < ActionController::Base
  def index
  	@leads = Lead.paginate(page: params[:page], per_page: 10)
  end

  def new
  	@lead = Lead.new
  end

  def create
  	# render plain: params[:lead].inspect
    # debugger
  	@lead = Lead.new(lead_params)
    @lead.user = User.first

  	if @lead.save

      UserMailer.registration_confirmation(@lead).deliver_now

  		flash[:notice] = "Lead was successfully created"
  		redirect_to lead_path(@lead)
  	else
  		render 'new'
  	end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy
    flash[:notice] = "Lead was successfully deleted"
    redirect_to leads_path
  end
  
  def show
  	@lead = Lead.find(params[:id])
  	# render json: @lead
  end

  def edit
  	@lead = Lead.find(params[:id])
  end

  def update
  	@lead = Lead.find(params[:id])
  	if @lead.update(lead_params)
  		flash[:notice] = "Lead was successfully updated"
	  	redirect_to lead_path(@lead)
	  else
	  	render 'edit'	
  	end
  end

  private
  	def lead_params
  		params.require(:lead).permit(:name, :phoneno, :email, :category)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
			if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end

	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
	
	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		
		if @user.save
			flash[:success] = "Welcome to the Leads page #{@user.username}"
			redirect_to leads_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	  	if @user.update(user_params)
	  		flash[:success] = "Your account was successfully updated"
		  	redirect_to leads_path
		  else
		  	render 'edit'	
	  	end
	end

	def show
		@user = User.find(params[:id])
	end

	
	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/home/welcome.html.erb
<h1>Welcome to spini leads page...</h1>
<%= link_to "Goto Leads page", leads_path %>

app/views/layouts/_header.html.erb
<div class="header">
	<img src="http://cdn.getspini.com/category/optimized/spini_white.png" />
</div>
<style type="text/css">
	.header{
		background-color: red;
		display: block;
		padding: 10px;
	}
	body{
		margin: 0;
	}
</style>

app/views/layouts/_messages.html.erb
<% flash.each do | name, msg| %>
	<ul>
		<li><%= msg %></li>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpiniPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/header.html.erb
<div class="header">
	<img src="http://cdn.getspini.com/category/optimized/spini_white.png" />
</div>
<style type="text/css">
	.header{
		background-color: #c00;
	}
</style>

app/views/leads/_form.html.erb
<% if @lead.errors.any? %>
	<ul>
		<% @lead.errors.full_messages.each do | msg | %>
		<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @lead do |l| %>
	<p>
		<%= l.label :name %><br>
		<%= l.text_field :name %>
	</p>
	<p>
		<%= l.label :phoneno %><br>
		<%= l.text_field :phoneno %>
	</p>
	<p>
		<%= l.label :email %><br>
		<%= l.text_field :email %>
	</p>
	<p>
		<%= l.label :category %><br>
		<%= l.text_field :category %>
	</p>
	<p>
		<%= l.submit %>
	</p>
<% end %>

<p>
	<%= link_to "Back to Lead page", leads_path %>
</p>

app/views/leads/_leads.html.erb
<%= render 'layouts/messages' %>
<p>
	<%= link_to "Create new lead", new_lead_path %>
</p>
<table border="1" style="border-collapse: collapse;">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Mobile Number</th>
		<th>Email Id</th>
		<th>Category</th>
		<th>Created_By</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th colspan="3">Settings</th>
	</tr>
	<% obj.each do |lead| %>
	<tr>
		<td><%= lead.id %></td>
		<td><%= lead.name %></td>
		<td><%= lead.phoneno %></td>
		<td><%= lead.email %></td>
		<td><%= lead.category %></td>
		<td><%= lead.user.username if lead.user %></td>
		<td><%= time_ago_in_words(lead.created_at) %> ago</td>
		<td><%= time_ago_in_words(lead.updated_at) %> ago</td>
		<td><%= link_to "Edit", edit_lead_path(lead) %></td>
		<td><%= link_to "Show", lead_path(lead) %></td>
		<td><a href=<%="/lead-delete/"+"#{lead.id}"%>>Delete</a></td>
	</tr>
	<% end %>
</table>

app/views/leads/edit.html.erb
<h1>Submit you new lead..here</h1>
<%= render 'form' %>

app/views/leads/index.html.erb
<h1>Listing all leads</h1>

<%= render 'leads', obj:@leads %>

<%= will_paginate %>

app/views/leads/new.html.erb
<h1>Submit you new lead..here</h1>

<%= render 'form' %>

app/views/leads/show.html.erb
<h1>Showing selected lead</h1>
<%= render 'layouts/messages' %>
<p>
	Name: <%= @lead.name %>
</p>
<p>
	phone number: <%= @lead.phoneno %>
</p>
<p>
	Email: <%= @lead.email %>
</p>
<p>
	Category: <%= @lead.category %>
</p>

<p>
	<%= link_to "Back to Lead page", leads_path %>
</p>
<p>
	<%= link_to "Edit", edit_lead_path(@lead) %>
</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<ul>
		<% @user.errors.full_messages.each do | msg | %>
		<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @user do |l| %>
	<p>
		<%= l.label :username %><br>
		<%= l.text_field :username %>
	</p>
	<p>
		<%= l.label :email %><br>
		<%= l.email_field :email %>
	</p>
	<p>
		<%= l.label :password %><br>
		<%= l.password_field :password %>
	</p>
	<p>
		<%= l.submit(@user.new_record? ? "Signup" : "Update Account") %>
	</p>
<% end %>

<p>
	<%= link_to "Back to user page", users_path %>
</p>

app/views/users/edit.html.erb
<h1>Edit User details</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
	<ul>
		<li>
			<p><%= link_to gravatar_for(user), user_path(user) %></p>
			<p><%= link_to user.username, user_path(user) %></p>
			<p><%= pluralize(user.leads.count, "article") if user.leads %></p>
		</li>
	</ul>
<% end %>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>View you user details</h1>
<h2>Welcome Mr. <%= @user.username %></h2>

<div class="col-md-4 col-md-offset-4 center">
	<%= gravatar_for @user, size: 150 %>
</div>

<h2><%= @user.username %>'s Leads list:</h2>

<%= render 'leads/leads', obj:@user.leads %>